name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pygithub
            GitPython
      - name: Run feedback script
        run: | 
          pwd
          ls -la
          REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          git update-index --chmod=+x ./feedback/feedback_test.py
          python ./feedback/feedback_test.py
          
      - name: add content to wiki
        run: |
          pwd
          git clone "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.wiki.git" repo_wiki
          mv -v wiki/* repo_wiki/
          cd repo_wiki
          git add .
          git commit -m "Generated Wiki"
          git push
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
        #   cd ${GITHUB_REPOSITORY}.wiki
          
        
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WIKI_DIR: ${{github.repository}}.wiki
          
        
          
