name: CI

on:
  push



jobs:
  generate_feedback:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pygithub
            GitPython
      - name: Run feedback script
        run: |
          pwd
          ls -la
          git update-index --chmod=+x ./feedback/feedback_test.py
          python ./feedback/feedback_test.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Checkout wiki code
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          ref: 'main'

      - name: add feedback log to wiki log
        run: |
          echo ${{github.repository}}
          mkdir -p .log
          cp ../feedback/feedback.md .log/feedback_$(date '+%s').md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add feedback to log"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:    # specify the wiki repo and push the update.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}.wiki
          branch: main

      - name: Checkout wiki code
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          ref: 'master'

      - name: concatinate feedback
        run: |
          mv feedback.md feedback_bak.md
          mv ../feedback/feedback.md ./feedback.md
          echo "\ --------------------------------------\" >> feedback.md
          cat feedback_bak.md >> feedback.md
          rm feedback_bak.md

      - name: add feedback wiki
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add feedback.md
          git commit -m "Update Feedback"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WIKI_DIR: ${{github.repository}}.wiki

      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@master
        with:    # specify the wiki repo and push the update.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}.wiki
          branch: master

      - name: Checkout repo code
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
          ref: 'main'

      - name: update readme file back to normal
        run: |
          pwd
          ls -la
          git update-index --chmod=+x ./feedback/feedback_change_readme.py
          python ./feedback/feedback_change_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
