name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pygithub
            GitPython
      - name: Run feedback script
        run: | 
          pwd
          ls -la
          git update-index --chmod=+x ./feedback/feedback_test.py
          python ./feedback/feedback_test.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WIKI_DIR: ${{github.repository}}.wiki
          
      - name: clone wiki
        run: |
          REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          cd ..
          git clone "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.wiki.git" 
          mv -v "$REPOSITORY_NAME"/wiki/* "$REPOSITORY_NAME".wiki/
      
          
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          
      - name: add content to wiki
        run: |
          cd ..
          pwd
          ls -la
          REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          cd "$REPOSITORY_NAME".wiki
          echo ${{ github.sender.login }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generated Wiki"
          git push
          
      #- uses: actions/checkout@v2
      #  with:
      #    repository: ${{github.repository}}.wiki
        #   cd ${GITHUB_REPOSITORY}.wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          WIKI_DIR: ${{github.repository}}.wiki
          
        
          
