name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: pygithub
      - name: Get_token
        id: Get_token
        uses: actions/Get_token@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run feedback script
        run: |
          git update-index --chmod=+x ./feedback/feedback_test.py
          python ./feedback/feedback_test.py
          
